language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.npm

env:
  global:
    - JOBS=1

before_install:
  - npm config set spin false
  - cd waldo/

install:
  - npm install
